name: Build Image and Push to Docker Hub

on:
  push:
    branches: ["release/*", "main"]

env:
  FOO: bar
  BASE_URL_LNX_SDK: https://storage.googleapis.com/flutter_infra_release/releases/stable/linux

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:

      - name: Install Base Packages
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Flutter SDK
        run: |
          curl -O $BASE_URL_LNX_SDK/flutter_linux_3.29.2-stable.tar.xz

      - name: Extracting Flutter SDK
        run: |
          tar xf flutter_linux_3.29.2-stable.tar.xz

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: rmoraes92/flutter:latest
