name: Build Image and Push to Docker Hub

on:
  push:
    branches: ["release/*"]

env:
  FOO: bar
  BASE_URL_LNX_SDK: https://storage.googleapis.com/flutter_infra_release/releases/stable/linux

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:

      - name: Install Base Packages
        run: sudo apt-get update && sudo apt-get install -y curl make

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Downloading and Extracting Flutter SDK
        run: |
          make assets/flutter

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from branch name
        id: extract_version
        run: |
          VERSION=$(make echo_git_release_version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: rmoraes92/flutter:${{ env.VERSION }}
