name: Rust

on:
  push:
    branches: ["release/*", "main"]

env:
  FOO: bar

jobs:
  build:
    needs: test
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install
        run: apt-get update && apt-get install -y curl

      - name: Run tests
        run: curl https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.29.2-stable.tar.xz -O flutter_linux_3.29.2-stable.tar.xz

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: rmoraes92/flutter:latest
